import { UiHeader, UiFooter } from '@/components';
import './globals.scss';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { RecoilProvider } from '@/lib';

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '700'], style: ['italic', 'normal'], variable: '--roboto' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang='en' className={roboto.className}>
      <body>
        <RecoilProvider>
          <UiHeader />
          {children}
          <UiFooter />
        </RecoilProvider>
      </body>
    </html>
  );
}
